### ISSUE TITLE
model / controller tests fail with watch 

### ISSUE THREAD

**Issue by danielbaak** [zand3rs/sails-test-helper#8]
When testing 

`Model.create()...`
or
`Controller.action()`

with the mocha `-w` flag set, the first execution of the tests works fine, further executions triggered by file changes fail with non-obvious errors.

E.g. `Model.create()` yields the following error and stack trace

```
Uncaught TypeError: Cannot call method 'insert' of undefined
    at Object.module.exports.adapter.create (node_modules/sails-disk/lib/adapter.js:136:28)
    at module.exports.create (node_modules/waterline/lib/waterline/adapter/dql.js:84:13)
    at bound.createValues (node_modules/waterline/lib/waterline/query/dql/create.js:214:16)
    at node_modules/waterline/lib/waterline/query/dql/create.js:74:20
    at node_modules/waterline/node_modules/async/lib/async.js:708:13
    at node_modules/waterline/node_modules/async/lib/async.js:49:16
    at node_modules/waterline/node_modules/async/lib/async.js:263:32
    at node_modules/waterline/node_modules/async/lib/async.js:40:16
    at node_modules/waterline/node_modules/async/lib/async.js:705:17
    at node_modules/waterline/node_modules/async/lib/async.js:49:16
    at node_modules/waterline/node_modules/async/lib/async.js:263:32
    at node_modules/waterline/node_modules/async/lib/async.js:40:16
    at bound.<anonymous> (node_modules/waterline/lib/waterline/utils/schema.js:151:44)
    at fn (node_modules/waterline/lib/waterline/utils/callbacksRunner.js:41:10)
    at node_modules/waterline/node_modules/async/lib/async.js:162:20
    at iterate (node_modules/waterline/node_modules/async/lib/async.js:256:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (node_modules/waterline/node_modules/async/lib/async.js:275:9)
    at Object.async.forEachSeries.async.eachSeries (node_modules/waterline/node_modules/async/lib/async.js:211:22)
    at Object.runner.beforeCreate (node_modules/waterline/lib/waterline/utils/callbacksRunner.js:44:9)
    at node_modules/waterline/lib/waterline/query/dql/create.js:180:17
    at node_modules/waterline/node_modules/async/lib/async.js:699:13
    at iterate (node_modules/waterline/node_modules/async/lib/async.js:256:13)
    at node_modules/waterline/node_modules/async/lib/async.js:268:29
    at node_modules/waterline/node_modules/async/lib/async.js:40:16
    at node_modules/waterline/node_modules/async/lib/async.js:705:17
    at node_modules/waterline/lib/waterline/query/validate.js:72:7
    at node_modules/waterline/node_modules/async/lib/async.js:708:13
    at node_modules/waterline/node_modules/async/lib/async.js:49:16
    at node_modules/waterline/node_modules/async/lib/async.js:263:32
    at node_modules/waterline/node_modules/async/lib/async.js:40:16
    at node_modules/waterline/node_modules/async/lib/async.js:705:17
    at node_modules/waterline/lib/waterline/query/validate.js:66:11
    at node_modules/waterline/node_modules/async/lib/async.js:49:16
    at node_modules/waterline/node_modules/async/lib/async.js:263:32
    at node_modules/waterline/node_modules/async/lib/async.js:40:16
    at node_modules/waterline/lib/waterline/query/validate.js:60:13
    at node_modules/waterline/lib/waterline/utils/schema.js:151:44
    at runner (node_modules/waterline/lib/waterline/query/validate.js:58:11)
    at node_modules/waterline/node_modules/async/lib/async.js:162:20
    at iterate (node_modules/waterline/node_modules/async/lib/async.js:256:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (node_modules/waterline/node_modules/async/lib/async.js:275:9)
    at Object.async.forEachSeries.async.eachSeries (node_modules/waterline/node_modules/async/lib/async.js:211:22)
    at node_modules/waterline/lib/waterline/query/validate.js:64:15
    at node_modules/waterline/node_modules/async/lib/async.js:699:13
    at iterate (node_modules/waterline/node_modules/async/lib/async.js:256:13)
```

**Comment by zand3rs** [comment]
please provide steps to replicate

**Comment by zand3rs** [comment]
closing issue due to lack of information
